<h1>NumPy Introduction</h1>
<p>
This notebook presents a small fraction of NumPy's methods. Read https://docs.scipy.org/doc/numpy/index.html for the whole documentation, https://docs.scipy.org/doc/numpy/user/quickstart.html for the official quick-start.
</p>
<p>
NumPy extends Python with optimized mathematic methods. Additionally, it implements every major matrix operation. NumPy is part of the SciPy project. Usually, mypy is bundled with common Python distributions, such as Anaconda (https://www.continuum.io/anaconda). If it is not bundled with your distribution and you use pip, you can install NumPy with the command "pip install numpy".
</p>
<p>
Once you have installed NumPy on your machine, you can load it into your Python programs:
</p>

In [2]:
import numpy

<h3>1. Basic Mathematical operations</h3>
NumPy provides fast methods (compared to Python's standard methods) for basic mathematical operations and values, either on single values or on NumPy matrices:

In [3]:
numpy.sin(numpy.pi/2)

1.0

In [4]:
numpy.exp(1) # e**1

2.7182818284590451

<h3>2. Enumerations</h3>
With numpy, you can generate basic enumerations which are often used in other scientific Python libraries.

In [42]:
# Numbers from 0 to 9
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# 5 equally distributed numbers in the interval [13; 17]
numpy.linspace(13, 17, 5, endpoint=True)

array([ 13.,  14.,  15.,  16.,  17.])

<h3>3. Numpy "array" class</h3>
NumPy's most important matrix class is "array". It is the representation of matrices. You can define single-lined or multidimensional arrays, and access them like a Python lists (or a list of lists):

In [5]:
single_lined = numpy.array([1,2,3])
single_lined

array([1, 2, 3])

In [49]:
# Access to single element.
single_lined[1]

2

In [40]:
multidimensional = numpy.arange(10)
multidimensional = multidimensional.reshape(5,2)
multidimensional

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
# Access to line
multidimensional[0]

array([0, 1])

In [51]:
# Access to single element
multidimensional[0][0]

0

For multidimensinal arrays, NumPy provides a convenient slice-based row and line access:

In [56]:
# Access to first row using slices
multidimensional[:,0]

array([0, 2, 4, 6, 8])

Arrays have attributes with additional information about them:

In [10]:
multidimensional.size

10

Similar to Python's standard lists, you can perform mathematical operations on the array elements directly:

In [41]:
single_lined*2

array([2, 4, 6])

In [12]:
numpy.exp(multidimensional)

array([[  1.00000000e+00,   2.71828183e+00],
       [  7.38905610e+00,   2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03]])

<h3>4. Basic matrix operations with "array"</h3>
All matrix calculations can be performed with NumPy arrays:

In [23]:
# The dot product
vector = numpy.array([2,4])
multidimensional.dot(vector)

array([ 4, 16, 28, 40, 52])

In [25]:
# This dot product does not work, as the dimensions do not fit
vector.dot(multidimensional)

ValueError: shapes (2,) and (5,2) not aligned: 2 (dim 0) != 5 (dim 0)

In [32]:
# Transposition
print(multidimensional)
print()
print(multidimensional.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [35]:
# Conjugated matrix (using complex numbers)
complex_vector = numpy.array([1+2j, 3+4j])
complex_vector.conj()

array([ 1.-2.j,  3.-4.j])

<h3>5. Linear algebra operations</h3>
Additionally, all special quadratic matrix operations can be performed with numy.array compatible methods, using numpy.linalg
(More information at http://docs.scipy.org/doc/numpy/reference/routines.linalg.html):

In [14]:
import numpy.linalg
square_array = numpy.arange(25).reshape(5,5)
square_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
# Return the quadratic matrix's determinant.
numpy.linalg.det(square_array) 

0.0

In [16]:
# Return the eigenvalues and (in order) the corresponding eigenvectors (in columns).
numpy.linalg.eig(square_array)

(array([  6.39116499e+01,  -3.91164992e+00,  -4.06523933e-15,
          2.58443073e-16,   1.51528038e-15]),
 array([[-0.0851802 ,  0.67779864, -0.46549901,  0.18772213, -0.00207481],
        [-0.23825372,  0.36348873,  0.55597991, -0.0514454 , -0.41636356],
        [-0.39132723,  0.04917881, -0.15590518, -0.65194893,  0.2955311 ],
        [-0.54440074, -0.2651311 ,  0.50586667,  0.70734553,  0.66632773],
        [-0.69747425, -0.57944101, -0.44044239, -0.19167334, -0.54342046]]))

In [17]:
# Access the eigenvector for the first eigenvalue. 
numpy.linalg.eig(square_array)[1][:,0]

array([-0.0851802 , -0.23825372, -0.39132723, -0.54440074, -0.69747425])

In [39]:
# Solve the linear matrix equation.
# Solved equation: 1*x1 - 3*x2 = 2 and 2*x1 + (3+5j)+x2 = -3
matrix = numpy.array([[1,-3], [2,4+5j]])
vector = numpy.array([2,-3])
numpy.linalg.solve(matrix, vector)

array([ 0.32+0.84j, -0.56+0.28j])

<h3>6. Polynomial operations</h3>

In [2]:
import numpy.polynomial
# Set x^3 + 2x^2 + 3x
p = numpy.polynomial.Polynomial([1, 2, 3])

# Get the roots of it
p.roots()

array([-0.33333333-0.47140452j, -0.33333333+0.47140452j])

In [3]:
# Get the degree
p.degree()

2

Polynomial fit (https://en.wikipedia.org/wiki/Chebyshev_polynomials):

In [13]:
# Fit cos to a polynomial
# For more complex fitting, you may use Scipy
x_points = numpy.linspace(0, numpy.pi, 100)
y_to_fit = numpy.cos(x_points)

# Get  polynomial fit up to the 10th degree
numpy.polynomial.Chebyshev.fit(x_points, y_to_fit, 10)

Chebyshev([ -8.50040650e-16,  -1.13364818e+00,   1.95734683e-15,
         1.38071776e-01,  -1.18317684e-15,  -4.49071453e-03,
         9.13246902e-16,   6.77006993e-05,  -5.77827989e-16,
        -5.90299662e-07,   9.37024407e-17], [ 0.        ,  3.14159265], [-1.,  1.])

<p>
numpy.array is the basic numeric data structure for all non-symbolic matrix operations which are used in the SciPy project. You can find it in Matplotlib, pandas, scipy.stats, and other SciPy and external modules.
</p>
<p>
You can enhance the performance of NumPy operations further if you use optimization techniques such as numba (http://numba.pydata.org/), Cython (http://cython.org/) or Theano (http://deeplearning.net/software/theano/).
</p>

PSB 2017