<h2>Scipy</h2>
This notebook shows the most important functions of Scipy, a Python library for scientific mathematical and statistical routines.

Usually, Scipy is bundled with common Python distribution, such as Anaconda (https://www.continuum.io/anaconda). If it is not bundled with your distribution and you use pip, you can install Scipy with the command "pip install scipy". A free book which is including lectures about Scipy can be found under http://www.scipy-lectures.org (most of the examples shown in this notebook are derived from this book).

After you installed Scipy on your device, you can import it into your Python scripts with the following commands:

In [2]:
from scipy import optimize
import numpy

<h3>1. Optimization</h3>

In [3]:
# The following function shall be searched for global minima
def to_optimize(x):
   return x**2 + 10*x

In [4]:
# The BFGS global minimum finder starts from a start point (here: 0)
# It may only find a local minimum, depending on the start point
optimize.fmin_bfgs(to_optimize, 0)

Optimization terminated successfully.
         Current function value: -25.000000
         Iterations: 3
         Function evaluations: 12
         Gradient evaluations: 4


array([-5.00000003])

In [5]:
# The basinhopper algorithm is an alternative to BFGS
# It is said to be more reliable than BFGS
optimize.basinhopping(to_optimize, 0)

                        fun: -25.000000000000004
 lowest_optimization_result:       fun: -25.000000000000004
 hess_inv: array([[ 0.5]])
      jac: array([ 0.])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([-5.00000003])
                    message: ['requested number of basinhopping iterations completed successfully']
      minimization_failures: 0
                       nfev: 1023
                        nit: 100
                       njev: 341
                          x: array([-5.00000003])

In [6]:
# In order to find a local minimum in an interval, an other method is used
optimize.fminbound(to_optimize, 0, 10)

5.3634455116374378e-06

In [7]:
# Find one of the roots of a function, probalby using an approximated Newton Method (the numeric parameter is an initial guess)
# In order to find more roots, other inital guesses have to be used
root = optimize.fsolve(to_optimize, 1)
root

array([ 0.])

<h3>2. Fitting</h3>

In [8]:
# Complex Curve Fitting
# We shall find parameters a and b which shall give the best fit to a number of points
# For polynomial fitting, you can also use NumPy
def to_fit(x, a, b):
    return a*(x/2) + b*x

xpoints = numpy.linspace(-5, 5, num=10)
ypoints = numpy.linspace(5, 15, num=10)
initial_guess = [0, 0]
parameters, paramameters_covariance = optimize.curve_fit(to_fit, xpoints, ypoints, initial_guess)
parameters

array([-13.01298105,   7.50649051])

In [9]:
paramameters_covariance

array([[  3.67507259e+17,  -1.83753628e+17],
       [ -1.83753628e+17,   9.18768130e+16]])

<h3>3. Numeric integration</h3>
For symbolic integration, you can use SymPy.

In [10]:
from scipy.integrate import quad

In [11]:
# quad is a very general integrator
result, error = quad(numpy.cos, 0, 1)
result

0.8414709848078965

In [12]:
from scipy.integrate import odeint

In [13]:
# This ordinary differential equation shall be solved (dy/dt=-y)...
def ode(y, t):
    return -y

In [14]:
# ... which is done by using odeint
timepoints = numpy.linspace(0, 4, 5)
yvector, information = odeint(ode, 1, timepoints,
                              args=(), full_output=True)

In [15]:
yvector

array([[ 1.        ],
       [ 0.36787947],
       [ 0.13533528],
       [ 0.04978706],
       [ 0.01831564]])

In [16]:
information

{'hu': array([ 0.12103171,  0.14945291,  0.18225891,  0.18225891]),
 'imxer': -1,
 'leniw': 21,
 'lenrw': 36,
 'message': 'Integration successful.',
 'mused': array([1, 1, 1, 1], dtype=int32),
 'nfe': array([53, 67, 81, 91], dtype=int32),
 'nje': array([0, 0, 0, 0], dtype=int32),
 'nqu': array([6, 6, 7, 7], dtype=int32),
 'nst': array([24, 31, 38, 43], dtype=int32),
 'tcur': array([ 1.10478577,  2.00885016,  3.12063254,  4.03192709]),
 'tolsf': array([  2.03060980e-321,   2.03060980e-321,   2.03060980e-321,
          2.03060980e-321]),
 'tsw': array([ 0.,  0.,  0.,  0.])}

<h3>4. Statistics</h3>

In [17]:
from scipy import stats

In [18]:
# Fit data points to normal distribution
to_fit = numpy.random.normal(size=100)
loc, std = stats.norm.fit(to_fit)
loc

0.06088385734433243

In [19]:
std

0.89161614529809119

In [20]:
# Random numbers should be used using NumPy
numpy.random.rand(5)

array([ 0.89186513,  0.39004951,  0.8990611 ,  0.72328141,  0.25901297])

Many more statistical methods and tests are available. A table of available routines can be found under https://docs.scipy.org/doc/scipy/reference/stats.html.

PSB 2017